name: reservation_system_customer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.25
  geolocator: ^5.3.0
  intl: ^0.16.1
  flutter_bloc: ^3.2.0
  hydrated_bloc: ^3.0.0
  equatable: ^1.1.1
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

