name: reservation_system_customer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.25
  geolocator: ^5.3.0
  intl: ^0.16.0
  flutter_bloc: ^3.2.0
  hydrated_bloc: ^3.0.0
  equatable: ^1.1.1
  provider: ^4.0.4
  fl_chart: ^0.8.6
  qr_flutter: ^3.0.1
  shared_preferences: ^0.5.6+3
  flutter_local_notifications: ^1.3.0
  json_annotation: ^3.0.1
  http: ^0.12.0+4
  device_identifier: ^1.0.2+2
  flutter_speed_dial: ^1.2.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  json_serializable: ^3.2.5
  build_runner: ^1.8.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/
    - lang/
